### ISSUE TITLE
Huge octocat covering entire page on Firefox 68.5.0esr

### ISSUE THREAD

**Issue by jackwilsdon** [bigardone/elm-css-patterns#1]
![image](https://user-images.githubusercontent.com/1843197/80581943-d585b280-8a05-11ea-9012-1ca52dee827f.png)

**Comment by bigardone** [comment]
😱 Thanks for reporting!

**Comment by bigardone** [comment]
I've tried in v76.0b8 (developer edition) and it is looking fine:

![image](https://user-images.githubusercontent.com/1090272/80786869-325ba700-8b85-11ea-8e13-f0f366d8e7d6.png)

EDIT: It turns out this is a reported issue of version 68 in which it does not support **rem** length units in SVGs https://bugzilla.mozilla.org/show_bug.cgi?id=1598929

Fix: https://github.com/bigardone/elm-css-patterns/commit/e5f352c4a3f43968fc42fc7a715760bc75dbf66b

Thanks again for reporting it 🙌
